version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/New_York"
    versioning-strategy: increase
    open-pull-requests-limit: 20
    insecure-external-code-execution: deny
    commit-message:
      prefix: "[bundler] "
    groups:
      sentry:
      patterns:
        - "sentry*"
